In [1]:
# 3.6复数的数学运算
"""问题
你写的最新的网络认证方案代码遇到了一个难题，并且你唯一的解决办法就是使用复数空间。 再或
者是你仅仅需要使用复数来执行一些计算操作。

解决方案
复数可以用使用函数 complex(real, imag) 或者是带有后缀j的浮点数来指定。比如："""
a = complex(2, 4)
b = 3 - 5j
a

(2+4j)

In [2]:
b

(3-5j)

In [3]:
a.real

2.0

In [4]:
b.imag

-5.0

In [5]:
a.conjugate()

(2-4j)

In [6]:
a + b

(5-1j)

In [7]:
a*b

(26+2j)

In [8]:
a/b

(-0.4117647058823529+0.6470588235294118j)

In [9]:
abs(a)

4.47213595499958

In [10]:
import cmath
cmath.sin(a)

(24.83130584894638-11.356612711218174j)

In [11]:
cmath.exp(a)

(-4.829809383269385-5.5920560936409816j)

In [12]:
"""讨论
Python中大部分与数学相关的模块都能处理复数。 比如如果你使用 numpy ，可以很容易的构造一个
复数数组并在这个数组上执行各种操作："""
import numpy as np
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
a

array([2.+3.j, 4.+5.j, 6.-7.j, 8.+9.j])

In [13]:
a+2

array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j])

In [14]:
np.sin(a)

array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

In [15]:
"""Python的标准数学函数确实情况下并不能产生复数值，因此你的代码中不可能会出现复数返回值。
比如："""
import math
math.sqrt(-1)

ValueError: math domain error

In [16]:
"""如果你想生成一个复数返回结果，你必须显示的使用 cmath 模块，或者在某个支持复数的库中声
明复数类型的使用。比如：

>>> import cmath
>>> cmath.sqrt(-1)
1j
>>>"""
cmath.sqrt(-1)

1j